import type { Category, Tag, UnitType } from '../src/types/product';

export interface SeedProduct {
  slug: string;
  name: string;
  category: Category;
  description: string;
  presentation: string;
  unitType: UnitType;
  tags: Tag[];
  featured: boolean;
  visible: boolean;
  order: number;
}

const p = (
  slug: string,
  name: string,
  category: Category,
  description: string,
  presentation: string,
  unitType: UnitType,
  tags: Tag[],
  order: number,
  featured = false,
): SeedProduct => ({
  slug,
  name,
  category,
  description,
  presentation,
  unitType,
  tags,
  featured,
  visible: true,
  order,
});

export const seedProducts: SeedProduct[] = [
  // ─── Longanizas y Vienesas Ahumadas ────────────────────────────────────
  p(
    'butifarra-coctel',
    'Butifarra Coctel',
    'longanizas-vienesas-ahumadas',
    'Butifarra pequeña ideal para cócteles y picoteos, elaborada con cortes seleccionados de cerdo y ahumada en roble austriaco.',
    'Sachet 6 uni · 400 g',
    'sachet',
    ['gondola', 'horeca'],
    100,
  ),
  p(
    'chistorra',
    'Chistorra',
    'longanizas-vienesas-ahumadas',
    'Embutido delgado de origen navarro, elaborado con carne de cerdo condimentada con pimentón, ideal para tapas y desayunos.',
    'Sachet 4 uni · 400 g',
    'sachet',
    ['gondola', 'horeca'],
    110,
  ),
  p(
    'longaniza-butifarra',
    'Longaniza Butifarra',
    'longanizas-vienesas-ahumadas',
    'Embutido tradicional de España a base de cortes de carne de cerdo finamente condimentado y ahumado con roble austriaco.',
    'Sachet 4 uni · 400 g',
    'sachet',
    ['gondola', 'horeca'],
    120,
  ),
  p(
    'longaniza-tipo-chillan',
    'Longaniza Tipo Chillán',
    'longanizas-vienesas-ahumadas',
    'Embutido tradicional chileno hecho de carne de cerdo adobada y embutida en tripa natural.',
    'Sachet 4 uni · 400 g',
    'sachet',
    ['gondola', 'horeca'],
    130,
  ),
  p(
    'mix-de-longanizas',
    'Mix de Longanizas',
    'longanizas-vienesas-ahumadas',
    'Una combinación de nuestras longanizas: Butifarra, Chillán, Polaca y Morcilla en una sola presentación.',
    'Sachet 4 uni · 400 g',
    'sachet',
    ['gondola', 'horeca'],
    140,
  ),
  p(
    'prieta-morcilla-boudin-frances',
    'Prieta o Morcilla "Boudin Français"',
    'longanizas-vienesas-ahumadas',
    'Receta francesa a base de cortes seleccionados de cerdo, sangre y cubos de tocino con un toque de nuez moscada y canela.',
    'Sachet 2 uni · 210 g',
    'sachet',
    ['gondola', 'horeca'],
    150,
  ),
  p(
    'vienesa-frankfurt',
    'Vienesa Frankfurt',
    'longanizas-vienesas-ahumadas',
    'Receta tradicional alemana preparada con carne seleccionada de cerdo y un toque ahumado en roble austriaco.',
    'Sachet 5 uni · 350 g',
    'sachet',
    ['gondola', 'horeca'],
    160,
  ),
  p(
    'salchicha-angus',
    'Salchicha Angus',
    'longanizas-vienesas-ahumadas',
    'Embutido preparado con carne seleccionada de vacuno Angus (100% animales a pastoreo, sin antibióticos ni hormonas), ahumado en roble austriaco.',
    'Sachet · aprox. 400 g',
    'sachet',
    ['gondola', 'horeca'],
    170,
  ),

  // ─── Productos Madurados ───────────────────────────────────────────────
  p(
    'guanciale-madurado',
    'Guanciale Madurado',
    'productos-madurados',
    'Deliciosa carrillada o papada de cerdo madurada en seco, perfecta para la elaboración de la pasta carbonara.',
    'Pieza 1 – 2 kg',
    'kg',
    ['horeca'],
    200,
    true,
  ),
  p(
    'coppa',
    'Coppa',
    'productos-madurados',
    'Cortes seleccionados de lomo de cerdo vetado y madurado en seco por 6 meses.',
    'Pieza 1,5 – 2 kg',
    'kg',
    ['gondola', 'horeca'],
    210,
    true,
  ),
  p(
    'chorizo-espanol',
    'Chorizo Español',
    'productos-madurados',
    'Carne de cerdo condimentada con el clásico Pimentón de La Vera y especias. Madurada en seco durante 4 meses.',
    'Pieza 2 – 2,5 kg',
    'kg',
    ['gondola', 'horeca'],
    220,
    true,
  ),
  p(
    'fuet-espanol',
    'Fuet Español',
    'productos-madurados',
    'Embutido de origen español, típico de la región de Cataluña, a base de cerdo, madurado en seco durante 4 meses.',
    'Unidad · 90 g',
    'unidad',
    ['gondola', 'horeca'],
    230,
    true,
  ),
  p(
    'fuet-cranberry',
    'Fuet con Cranberries',
    'productos-madurados',
    'Siguiendo la receta tradicional catalana, embutido de cerdo madurado con arándanos rojos para un toque agridulce, ideal para maridar con vinos tintos.',
    'Unidad · 90 g',
    'unidad',
    ['gondola', 'horeca'],
    240,
  ),
  p(
    'bresaola',
    'Bresaola',
    'productos-madurados',
    'Filete de ternera magro, salado y madurado en seco por 6 meses.',
    'Pieza 1,5 – 2 kg',
    'kg',
    ['horeca'],
    250,
  ),
  p(
    'cabanossi-polaco',
    'Cabanossi Polaco',
    'productos-madurados',
    'Embutido polaco tradicional, delgado y ahumado, ideal para tabla, snack o picoteo.',
    'Pieza · aprox. 2 kg',
    'kg',
    ['gondola', 'horeca'],
    260,
  ),
  p(
    'lomo-embuchado',
    'Lomo Embuchado',
    'productos-madurados',
    'Solomillo de cerdo tradicional español, salado y madurado en seco por 4 meses.',
    'Pieza 1 – 1,5 kg',
    'kg',
    ['horeca'],
    270,
  ),
  p(
    'panceta-madurada',
    'Panceta Madurada',
    'productos-madurados',
    'Cortes seleccionados de cerdo con textura jugosa, sabor salado y ahumado en roble austriaco.',
    'Pieza 2 – 2,5 kg',
    'kg',
    ['horeca'],
    280,
  ),
  p(
    'pastirma-de-cerdo',
    'Pastirma de Cerdo',
    'productos-madurados',
    'Carne de cerdo madurada y finamente condimentada, popular en Turquía y los países vecinos.',
    'Pieza 1,5 – 2 kg',
    'kg',
    ['horeca'],
    290,
  ),
  p(
    'pastirma-de-vacuno',
    'Pastirma de Vacuno',
    'productos-madurados',
    'Carne de res madurada y finamente condimentada, popular en Turquía y los países vecinos.',
    'Pieza 1,5 – 2 kg',
    'kg',
    ['horeca'],
    295,
  ),
  p(
    'pepperoni-madurado',
    'Pepperoni Madurado',
    'productos-madurados',
    'Pepperoni artesanal madurado en seco durante 4 meses, ideal para pizzería y tablas.',
    'Pieza 2 – 2,5 kg',
    'kg',
    ['gondola', 'horeca'],
    300,
  ),
  p(
    'salame-milano',
    'Salame Milano',
    'productos-madurados',
    'Salami de gran calibre condimentado con granos de pimienta negra, madurado en seco durante 4 meses.',
    'Pieza 2,5 – 3,5 kg',
    'kg',
    ['gondola', 'horeca'],
    310,
  ),
  p(
    'salame-angus',
    'Salame Angus',
    'productos-madurados',
    'Salami elaborado con carne de vacuno Angus y cortes seleccionados, madurado en seco.',
    'Pieza 2 – 2,5 kg',
    'kg',
    ['horeca'],
    320,
  ),
  p(
    'salame-italiano',
    'Salame Italiano',
    'productos-madurados',
    'Salami italiano artesanal madurado en seco durante 4 meses.',
    'Pieza 2 – 2,5 kg',
    'kg',
    ['gondola', 'horeca'],
    330,
  ),
  p(
    'jamon-serrano',
    'Jamón Serrano',
    'productos-madurados',
    'Jamón serrano español curado artesanalmente. Presentación laminada para carta y tabla.',
    'Envase · 500 g',
    'unidad',
    ['gondola', 'horeca'],
    340,
  ),

  // ─── Charqui ───────────────────────────────────────────────────────────
  p(
    'charqui-vacuno',
    'Charqui de Vacuno',
    'charqui',
    'Finos cortes de carne de vacuno salados, deshidratados y condimentados solo con sal de mar.',
    'Sachet · 30 g',
    'sachet',
    ['gondola', 'horeca'],
    400,
  ),
  p(
    'charqui-cerdo',
    'Charqui de Cerdo',
    'charqui',
    'Finos cortes de lomo de cerdo salados y deshidratados, condimentados con especias naturales.',
    'Sachet · 30 g',
    'sachet',
    ['gondola', 'horeca'],
    410,
  ),

  // ─── Productos Cocidos ─────────────────────────────────────────────────
  p(
    'arrollado-huaso',
    'Arrollado Huaso',
    'productos-cocidos',
    'Arrollado tradicional chileno de cerdo, cocido y condimentado con ají y ajo.',
    'Pieza · aprox. 200 g',
    'unidad',
    ['gondola', 'horeca'],
    500,
  ),
  p(
    'porchetta',
    'Porchetta',
    'productos-cocidos',
    'Porchetta italiana de cerdo deshuesado, aromatizada con hierbas y horneada lentamente. Mínimo 1 pieza.',
    'Pieza 4 – 5 kg',
    'unidad',
    ['horeca'],
    510,
  ),
  p(
    'chicharron',
    'Chicharrón',
    'productos-cocidos',
    'Deliciosos cortes de cerdo horneados, super crocantes, ideales para dieta keto.',
    'Granel · 1 kg',
    'kg',
    ['gondola', 'horeca'],
    520,
  ),
  p(
    'chuleta-kassler',
    'Chuleta Kassler',
    'productos-cocidos',
    'Chuleta de cerdo curada y ahumada al estilo alemán, jugosa y aromática.',
    'Pieza 5 – 6 kg',
    'kg',
    ['horeca'],
    530,
  ),
  p(
    'chuleta-ahumada',
    'Chuleta Ahumada',
    'productos-cocidos',
    'Cortes de cerdo seleccionados con textura suave y sabor ahumado en roble austriaco.',
    'Pieza · variable',
    'kg',
    ['horeca'],
    540,
  ),
  p(
    'jamon-pierna-cocido',
    'Jamón de Pierna Cocido',
    'productos-cocidos',
    'Jamón elaborado con la pierna entera del cerdo, cocido lentamente.',
    'Pieza 4 – 5 kg',
    'kg',
    ['horeca'],
    550,
  ),
  p(
    'jamon-pierna-ahumado-artesanal',
    'Jamón de Pierna Ahumado Artesanal',
    'productos-cocidos',
    'Jamón de pierna entera artesanal, ahumado en roble austriaco.',
    'Pieza 4 – 5 kg',
    'kg',
    ['horeca'],
    560,
  ),
  p(
    'lomo-kassler',
    'Lomo Kassler',
    'productos-cocidos',
    'Lomo de cerdo curado y ahumado al estilo alemán, ideal para lonjas.',
    'Pieza 1,5 – 2 kg',
    'kg',
    ['horeca'],
    570,
  ),
  p(
    'lomo-kassler-medallon',
    'Lomo Kassler (Medallón)',
    'productos-cocidos',
    'Presentación en medallones del clásico Lomo Kassler, listos para plancha o sándwich.',
    'Pack · 10 unidades',
    'unidad',
    ['gondola', 'horeca'],
    580,
  ),
  p(
    'cervelat',
    'Cervelat',
    'productos-cocidos',
    'Salami cocido típico finlandés, finamente condimentado.',
    'Pieza · variable',
    'kg',
    ['gondola', 'horeca'],
    590,
  ),
  p(
    'jamon-cocido',
    'Jamón Cocido',
    'productos-cocidos',
    'Jamón tradicional elaborado con la pierna del cerdo, sabor artesanal único.',
    'Pieza · variable',
    'kg',
    ['gondola', 'horeca'],
    600,
  ),
  p(
    'mortadela-italiana-pistacho',
    'Mortadela Italiana con Pistacho',
    'productos-cocidos',
    'Receta italiana preparada con carne de cerdo, pistachos y esencia de almendra.',
    'Pieza · aprox. 4 kg',
    'kg',
    ['gondola', 'horeca'],
    610,
  ),
  p(
    'pastrami-cerdo',
    'Pastrami de Cerdo',
    'productos-cocidos',
    'Cecina de cerdo ahumada en roble austriaco, finamente condimentada con pimienta negra y paprika, ideal para sándwiches.',
    'Pieza 1,5 – 2 kg',
    'kg',
    ['horeca'],
    620,
  ),
  p(
    'pastrami-vacuno',
    'Pastrami de Vacuno',
    'productos-cocidos',
    'Cecina de vacuno ahumada en roble austriaco, finamente condimentada con pimienta negra y paprika, ideal para sándwiches fríos.',
    'Pieza 2 – 2,5 kg',
    'kg',
    ['horeca'],
    630,
  ),
  p(
    'panceta-ahumada',
    'Panceta Ahumada',
    'productos-cocidos',
    'Cecina con carne seleccionada de cerdo, ahumada en roble austriaco.',
    'Pieza 2 – 2,5 kg',
    'kg',
    ['horeca'],
    640,
  ),
  p(
    'pastrami-americano-angus',
    'Pastrami Americano Angus',
    'productos-cocidos',
    'Pastrami americano elaborado con carne de vacuno Angus, ahumado y condimentado con especias.',
    'Pieza 3 – 4 kg',
    'kg',
    ['horeca'],
    650,
  ),
  p(
    'queso-cabra-ahumado',
    'Queso de Cabra Ahumado',
    'productos-cocidos',
    'Queso de cabra ahumado con roble austriaco, sabor intenso y aromático.',
    'Pieza · aprox. 4 kg',
    'kg',
    ['horeca'],
    660,
  ),
  p(
    'queso-gouda-ahumado',
    'Queso Gouda Ahumado',
    'productos-cocidos',
    'Queso Gouda con aroma y sabor característicos del proceso de ahumado en roble austriaco.',
    'Pieza 3,5 – 4 kg',
    'kg',
    ['horeca'],
    670,
  ),
  p(
    'salmon-ahumado-frio',
    'Salmón Ahumado al Frío',
    'productos-cocidos',
    'Salmón ahumado en frío al estilo tradicional, textura sedosa y sabor delicado.',
    'Pieza · variable',
    'kg',
    ['horeca'],
    680,
  ),
  p(
    'costillar-cerdo-ahumado',
    'Costillar de Cerdo Ahumado',
    'productos-cocidos',
    'Jugosas costillas de cerdo maceradas por varios días y ahumadas con roble austriaco.',
    'Pieza · variable',
    'kg',
    ['horeca'],
    690,
  ),
  p(
    'pate-de-campo',
    'Paté de Campo',
    'productos-cocidos',
    'Embutido elaborado con carne de cerdo e hígado de ternera, emulsificado con finas hierbas para una textura sedosa.',
    'Envase · 125 g',
    'unidad',
    ['gondola', 'horeca'],
    700,
  ),

  // ─── Untables ──────────────────────────────────────────────────────────
  p(
    'pepperoni-untable',
    'Pepperoni Untable',
    'untables',
    'Presentación untable del clásico pepperoni, ideal para tabla y aperitivos.',
    'Envase · 110 g',
    'unidad',
    ['gondola'],
    800,
  ),
  p(
    'sobrasada-untable',
    'Sobrasada Untable',
    'untables',
    'Embutido untable elaborado con carne de cerdo y especias, originario de Mallorca.',
    'Envase · 200 g',
    'unidad',
    ['gondola', 'horeca'],
    810,
  ),
  p(
    'tocino-aleman-untable',
    'Tocino Alemán Untable',
    'untables',
    'Untable de tocino ahumado al estilo alemán, aromático y cremoso.',
    'Envase · 110 g',
    'unidad',
    ['gondola'],
    820,
  ),

  // ─── Tablas ────────────────────────────────────────────────────────────
  p(
    'tabla-charcutera-150g',
    'Tabla Charcutera · 150 g',
    'tablas',
    'Combinación de tres productos madurados premium: Salame Italiano, Chorizo Español y Coppa. Presentación 150 g.',
    'Bandeja · 150 g',
    'unidad',
    ['gondola'],
    900,
  ),
  p(
    'tabla-charcutera-200g',
    'Tabla Charcutera · 200 g',
    'tablas',
    'Combinación de tres productos madurados premium: Salame Italiano, Chorizo Español y Coppa. Presentación 200 g.',
    'Bandeja · 200 g',
    'unidad',
    ['gondola'],
    910,
  ),
];
